In [85]:
import pandas as pd
import numpy as np

In [86]:
df = pd.read_csv(r"C:\Users\om sai compurer1\Desktop\cust satisfaction\cust_satisfaction.csv")

In [87]:
df

,Gender,Customer Type,Type of Travel,Class,satisfaction,Age,Flight Distance,Inflight entertainment,Baggage handling,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes
0,Male,Loyal Customer,Personal Travel,Eco Plus,neutral or dissatisfied,13,460,5,4,5,25,18.0
1,Male,disloyal Customer,Business travel,Business,neutral or dissatisfied,25,235,1,3,1,1,6.0
2,Female,Loyal Customer,Business travel,Business,satisfied,26,1142,5,4,5,0,0.0
3,Female,Loyal Customer,Business travel,Business,neutral or dissatisfied,25,562,2,3,2,11,9.0
4,Male,Loyal Customer,Business travel,Business,satisfied,61,214,3,4,3,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
103899,Female,disloyal Customer,Business travel,Eco,neutral or dissatisfied,23,192,2,4,2,3,0.0
103900,Male,Loyal Customer,Business travel,Business,satisfied,49,2347,5,5,4,0,0.0
103901,Male,disloyal Customer,Business travel,Business,neutral or dissatisfied,30,1995,4,4,4,7,14.0
103902,Female,disloyal Customer,Business travel,Eco,neutral or dissatisfied,22,1000,1,1,1,0,0.0
103903,Male,Loyal Customer,Business travel,Business,neutral or dissatisfied,27,1723,1,4,1,0,0.0

In [88]:
df['Gender'].unique()

<StringArray>
['Male', 'Female']
Length: 2, dtype: str

In [89]:
Gender ={
    'Male':0, 'Female':1
}

In [90]:
df['Gender'] = df['Gender'].map(Gender)

In [91]:
df['Customer Type'].unique()

<StringArray>
['Loyal Customer', 'disloyal Customer']
Length: 2, dtype: str

In [92]:
Customer_Type ={
    'Loyal Customer':0, 'disloyal Customer':1
}

In [93]:
df['Customer Type']= df['Customer Type'].map(Customer_Type)

In [94]:
df

,Gender,Customer Type,Type of Travel,Class,satisfaction,Age,Flight Distance,Inflight entertainment,Baggage handling,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes
0,0,0,Personal Travel,Eco Plus,neutral or dissatisfied,13,460,5,4,5,25,18.0
1,0,1,Business travel,Business,neutral or dissatisfied,25,235,1,3,1,1,6.0
2,1,0,Business travel,Business,satisfied,26,1142,5,4,5,0,0.0
3,1,0,Business travel,Business,neutral or dissatisfied,25,562,2,3,2,11,9.0
4,0,0,Business travel,Business,satisfied,61,214,3,4,3,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
103899,1,1,Business travel,Eco,neutral or dissatisfied,23,192,2,4,2,3,0.0
103900,0,0,Business travel,Business,satisfied,49,2347,5,5,4,0,0.0
103901,0,1,Business travel,Business,neutral or dissatisfied,30,1995,4,4,4,7,14.0
103902,1,1,Business travel,Eco,neutral or dissatisfied,22,1000,1,1,1,0,0.0
103903,0,0,Business travel,Business,neutral or dissatisfied,27,1723,1,4,1,0,0.0

In [95]:
df['Type of Travel'].unique()

<StringArray>
['Personal Travel', 'Business travel']
Length: 2, dtype: str

In [96]:
Type_of_Travel ={
    'Business travel':0, 'Personal Travel':1
}
df['Type of Travel']= df['Type of Travel'].map(Type_of_Travel)

In [97]:
df['Class'].unique()
Class ={
    'Business':0, 'Eco':1, 'Eco Plus':2
}
df['Class']= df['Class'].map(Class)
df

,Gender,Customer Type,Type of Travel,Class,satisfaction,Age,Flight Distance,Inflight entertainment,Baggage handling,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes
0,0,0,1,2,neutral or dissatisfied,13,460,5,4,5,25,18.0
1,0,1,0,0,neutral or dissatisfied,25,235,1,3,1,1,6.0
2,1,0,0,0,satisfied,26,1142,5,4,5,0,0.0
3,1,0,0,0,neutral or dissatisfied,25,562,2,3,2,11,9.0
4,0,0,0,0,satisfied,61,214,3,4,3,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
103899,1,1,0,1,neutral or dissatisfied,23,192,2,4,2,3,0.0
103900,0,0,0,0,satisfied,49,2347,5,5,4,0,0.0
103901,0,1,0,0,neutral or dissatisfied,30,1995,4,4,4,7,14.0
103902,1,1,0,1,neutral or dissatisfied,22,1000,1,1,1,0,0.0
103903,0,0,0,0,neutral or dissatisfied,27,1723,1,4,1,0,0.0

In [98]:
df['satisfaction'].unique()

<StringArray>
['neutral or dissatisfied', 'satisfied']
Length: 2, dtype: str

In [99]:
satisfaction ={
    'neutral or dissatisfied':0, 'satisfied':1
}
df['satisfaction']= df['satisfaction'].map(satisfaction)
df

,Gender,Customer Type,Type of Travel,Class,satisfaction,Age,Flight Distance,Inflight entertainment,Baggage handling,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes
0,0,0,1,2,0,13,460,5,4,5,25,18.0
1,0,1,0,0,0,25,235,1,3,1,1,6.0
2,1,0,0,0,1,26,1142,5,4,5,0,0.0
3,1,0,0,0,0,25,562,2,3,2,11,9.0
4,0,0,0,0,1,61,214,3,4,3,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
103899,1,1,0,1,0,23,192,2,4,2,3,0.0
103900,0,0,0,0,1,49,2347,5,5,4,0,0.0
103901,0,1,0,0,0,30,1995,4,4,4,7,14.0
103902,1,1,0,1,0,22,1000,1,1,1,0,0.0
103903,0,0,0,0,0,27,1723,1,4,1,0,0.0

In [100]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 103904 entries, 0 to 103903
Data columns (total 12 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   Gender                      103904 non-null  int64
 1   Customer Type               103904 non-null  int64
 2   Type of Travel              103904 non-null  int64
 3   Class                       103904 non-null  int64
 4   satisfaction                103904 non-null  int64
 5   Age                         103904 non-null  int64
 6   Flight Distance             103904 non-null  int64
 7   Inflight entertainment      103904 non-null  int64
 8   Baggage handling            103904 non-null  int64
 9   Cleanliness                 103904 non-null  int64
 10  Departure Delay in Minutes  103904 non-null  int64
 11  Arrival Delay in Minutes    103594 non-null  float64
dtypes: float64(1), int64(11)
memory usage: 9.5 MB

In [101]:
x = df.drop('satisfaction', axis=1)
y = df['satisfaction']

In [102]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(df.drop('satisfaction', axis=1), df['satisfaction'], test_size=0.2, random_state=42)

In [103]:
x_train

,Gender,Customer Type,Type of Travel,Class,Age,Flight Distance,Inflight entertainment,Baggage handling,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes
20921,1,0,1,1,59,1046,2,3,4,12,3.0
36897,1,1,0,0,40,752,1,4,1,19,29.0
8468,0,0,1,1,65,383,1,5,1,0,0.0
53490,1,0,1,1,70,2239,5,5,5,0,0.0
78687,1,1,0,1,25,1358,1,3,1,3,15.0
...,...,...,...,...,...,...,...,...,...,...,...
54886,0,1,0,1,39,637,3,2,3,1,0.0
76820,0,0,1,1,17,646,3,2,3,0,2.0
103694,0,0,0,1,46,1197,4,3,1,260,263.0
860,1,0,0,1,37,320,5,4,5,0,0.0
15795,1,0,1,1,14,351,4,5,4,0,0.0

In [104]:
y_train

20921     0
36897     0
8468      0
53490     0
78687     0
         ..
54886     0
76820     0
103694    0
860       1
15795     0
Name: satisfaction, Length: 83123, dtype: int64

In [105]:
x_test

,Gender,Customer Type,Type of Travel,Class,Age,Flight Distance,Inflight entertainment,Baggage handling,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes
80638,1,0,1,1,26,861,5,4,5,0,0.0
43398,0,0,0,0,22,393,3,3,3,0,16.0
32751,1,0,1,1,59,196,4,4,4,37,34.0
33571,1,0,1,1,32,1020,4,4,4,27,4.0
71287,0,1,0,0,35,1117,2,3,2,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
8158,0,1,0,0,42,236,1,4,1,0,0.0
53718,0,0,1,1,14,558,5,5,5,0,0.0
33319,0,0,1,1,9,1005,5,2,5,1,0.0
99162,1,0,0,0,45,3234,4,4,3,0,19.0
96811,0,0,0,2,31,86,4,1,4,0,0.0

In [106]:
y_test

80638    0
43398    0
32751    0
33571    0
71287    0
        ..
8158     0
53718    0
33319    0
99162    1
96811    1
Name: satisfaction, Length: 20781, dtype: int64

In [107]:
df.dropna()

,Gender,Customer Type,Type of Travel,Class,satisfaction,Age,Flight Distance,Inflight entertainment,Baggage handling,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes
0,0,0,1,2,0,13,460,5,4,5,25,18.0
1,0,1,0,0,0,25,235,1,3,1,1,6.0
2,1,0,0,0,1,26,1142,5,4,5,0,0.0
3,1,0,0,0,0,25,562,2,3,2,11,9.0
4,0,0,0,0,1,61,214,3,4,3,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
103899,1,1,0,1,0,23,192,2,4,2,3,0.0
103900,0,0,0,0,1,49,2347,5,5,4,0,0.0
103901,0,1,0,0,0,30,1995,4,4,4,7,14.0
103902,1,1,0,1,0,22,1000,1,1,1,0,0.0
103903,0,0,0,0,0,27,1723,1,4,1,0,0.0

In [108]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()

In [109]:
from sklearn.svm import SVC
sv = SVC()

In [110]:
x_train

,Gender,Customer Type,Type of Travel,Class,Age,Flight Distance,Inflight entertainment,Baggage handling,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes
20921,1,0,1,1,59,1046,2,3,4,12,3.0
36897,1,1,0,0,40,752,1,4,1,19,29.0
8468,0,0,1,1,65,383,1,5,1,0,0.0
53490,1,0,1,1,70,2239,5,5,5,0,0.0
78687,1,1,0,1,25,1358,1,3,1,3,15.0
...,...,...,...,...,...,...,...,...,...,...,...
54886,0,1,0,1,39,637,3,2,3,1,0.0
76820,0,0,1,1,17,646,3,2,3,0,2.0
103694,0,0,0,1,46,1197,4,3,1,260,263.0
860,1,0,0,1,37,320,5,4,5,0,0.0
15795,1,0,1,1,14,351,4,5,4,0,0.0

In [111]:
x_train.shape

(83123, 11)

In [112]:
y_train.shape

(83123,)

In [113]:
print(x_train.dtypes)

Gender                          int64
Customer Type                   int64
Type of Travel                  int64
Class                           int64
Age                             int64
Flight Distance                 int64
Inflight entertainment          int64
Baggage handling                int64
Cleanliness                     int64
Departure Delay in Minutes      int64
Arrival Delay in Minutes      float64
dtype: object

In [114]:
print(x_train.isnull().sum())

Gender                          0
Customer Type                   0
Type of Travel                  0
Class                           0
Age                             0
Flight Distance                 0
Inflight entertainment          0
Baggage handling                0
Cleanliness                     0
Departure Delay in Minutes      0
Arrival Delay in Minutes      251
dtype: int64

In [115]:
x_train = x_train.fillna(x_train.mean())

In [116]:
x_train['Arrival Delay in Minutes'] = x_train['Arrival Delay in Minutes'].fillna(x_train['Arrival Delay in Minutes'].mean())

In [117]:
lr.fit(x_train, y_train)

LinearRegression()

In [118]:
print(x_train.isnull().sum())

Gender                        0
Customer Type                 0
Type of Travel                0
Class                         0
Age                           0
Flight Distance               0
Inflight entertainment        0
Baggage handling              0
Cleanliness                   0
Departure Delay in Minutes    0
Arrival Delay in Minutes      0
dtype: int64

In [120]:
print(x_test.isnull().sum())

Gender                         0
Customer Type                  0
Type of Travel                 0
Class                          0
Age                            0
Flight Distance                0
Inflight entertainment         0
Baggage handling               0
Cleanliness                    0
Departure Delay in Minutes     0
Arrival Delay in Minutes      59
dtype: int64

In [122]:
x_test = x_test.fillna(x_test.mean())

In [123]:
lr.predict(x_test)

array([0.3226039 , 0.62751943, 0.21216606, ..., 0.19028965, 0.76368331,
       0.34747384], shape=(20781,))

In [124]:
lr.predict(x_train)

array([0.07994697, 0.14561407, 0.0161763 , ..., 0.32221064, 0.76934879,
       0.28777743], shape=(83123,))

In [127]:
sv.fit(x_train, y_train)

SVC()

In [128]:
sv.predict(x_test)

array([0, 0, 0, ..., 0, 1, 0], shape=(20781,))

In [129]:
sv.predict(x_train)

array([0, 0, 0, ..., 0, 0, 0], shape=(83123,))

In [131]:
import imblearn
from imblearn.over_sampling import SMOTE

In [132]:
from sklearn.tree import DecisionTreeRegressor

In [133]:
dtc = DecisionTreeRegressor()
dtc.fit(x_train,y_train)
pred = dtc.predict(x_test)
pred

array([0., 0., 0., ..., 1., 1., 1.], shape=(20781,))

In [134]:
dtc.get_params()

{'ccp_alpha': 0.0,
 'criterion': 'squared_error',
 'max_depth': None,
 'max_features': None,
 'max_leaf_nodes': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'random_state': None,
 'splitter': 'best'}

In [135]:
import joblib
joblib.dump(dtc, 'cust_satisfaction_model.lb')

['cust_satisfaction_model.lb']

In [136]:
cust_satisfaction_model = joblib.load('cust_satisfaction_model.lb')

In [137]:
cust_satisfaction_model

DecisionTreeRegressor()

In [138]:
cust_satisfaction_model.predict(x_test)

array([0., 0., 0., ..., 1., 1., 1.], shape=(20781,))

In [139]:
from sklearn.naive_bayes import GaussianNB
from sklearn.datasets import load_iris
x ,y = load_iris(return_X_y=True)
from sklearn.naive_bayes import GaussianNB, MultinomialNB
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=7)
Mnb =MultinomialNB()
Mnb.fit(x_train, y_train)

MultinomialNB()

In [140]:
Mnb.score(x_test, y_test)

0.8333333333333334

In [141]:
from sklearn.cluster import KMeans
km =KMeans()
km.fit(x_train, y_train)

KMeans()

In [142]:
km.score(x_test, y_test)

-9.296924697199538

In [145]:
df.to_csv('cust_satisfaction_model_cleaned.csv', index=False)